import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[url('/back.jpg')] bg-cover bg-center bg-no-repeat bg-blend-color-burn  h-screen w-full select-none font-serif overflow-hidden">
        <Header />
        {children}
      </body>
    </html>
  );
}
