import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "ShopFlower",
  description: "Generated by Bassem Samaali",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link
          rel="apple-touch-icon"
          href="/apple-icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body className="bg-[url('/back.jpg')] bg-cover bg-center bg-no-repeat bg-blend-color-burn  h-screen w-full select-none font-serif overflow-hidden">
        <Header />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
